/**
  ******************************************************************************
  * @file    mmc_transfer.h
  * @brief   DMA-backed, cache-safe wrappers around the eMMC block read/write
  *          used by both the USB MSC storage interface (usbd_storage_if.c)
  *          and the FatFs disk driver (user_diskio.c).
  *
  * Why this exists: the blocking HAL_MMC_ReadBlocks()/HAL_MMC_WriteBlocks()
  * on this HAL version do not use DMA/IDMA at all - they poll the SDMMC
  * RX/TX FIFO word-by-word in a CPU loop (see
  * Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mmc.c, "Read block(s) in
  * polling mode"). Called with HAL_MAX_DELAY, that fully occupies the CPU for
  * the whole transfer - and on the USB MSC path it happens synchronously
  * inside OTG_FS_IRQHandler.
  *
  * These wrappers instead kick off HAL_MMC_ReadBlocks_DMA()/WriteBlocks_DMA()
  * (SDMMC IDMA, no CPU involvement in the byte transfer) and wait for
  * completion signalled by HAL_MMC_RxCpltCallback()/TxCpltCallback()/
  * ErrorCallback(), implemented in mmc_transfer.c, which fire from
  * SDMMC1_IRQn (via the existing HAL_MMC_IRQHandler in stm32h7xx_it.c).
  *
  * Bounce buffer, not cache-maintenance-by-address: DMA always transfers
  * into/out of a fixed, non-cacheable static buffer owned by mmc_transfer.c
  * (see .mmc_dma_sec in STM32H750XX_FLASH.ld / MPU_Config() in main.c), and
  * the caller's buffer is only ever touched by the CPU via memcpy(). We do
  * NOT run SCB_Clean/InvalidateDCache_by_Addr() on the caller's buffer,
  * because on the FatFs/httpd path that buffer is `hs->buf` - allocated by
  * lwIP's own mem_malloc() (MEM_ALIGNMENT=4 in lwipopts.h) deep inside
  * Middlewares/.../httpd.c, packed tightly against other lwIP heap objects.
  * Rounding a Clean/Invalidate call out to enclosing 32-byte cache lines on
  * an under-aligned buffer we don't own corrupts whatever neighboring heap
  * object shares that cache line - this was diagnosed as the cause of a
  * full system lockup (all FreeRTOS tasks starved, only the tick ISR still
  * running) the first time the HTTP server touched eMMC after FreeRTOS was
  * added. The bounce buffer sidesteps this entirely: DMA never touches
  * memory whose alignment we don't control.
  *
  * NOTE for future FreeRTOS integration: MMC_WaitForComplete() in
  * mmc_transfer.c is the single place that busy-waits today. Once ready,
  * replace its body with osSemaphoreAcquire()/give it from the same
  * HAL_MMC_*CpltCallback - no caller of MMC_ReadBlocks()/MMC_WriteBlocks()
  * needs to change. The USB MSC callers (usbd_storage_if.c) run inside a
  * hardware ISR (OTG_FS_IRQHandler) and must keep using the spin-wait variant
  * - only FatFs-path callers (user_diskio.c), which run in task/thread
  * context, could switch MMC_WaitForComplete() to a real RTOS wait. The
  * s_xferBusy re-entrancy guard is IRQ-mask based for the same reason - a
  * real FreeRTOS mutex (e.g. SdmmcMutexHandle) must never be acquired from
  * OTG_FS_IRQHandler (mutex take/give is not valid ISR-context FreeRTOS
  * usage); if a task-side mutex is added later, keep this IRQ-mask guard
  * underneath it to still exclude the USB MSC ISR path.
  *
  * Deliberately NOT touched: Middlewares/ST/STM32_USB_Device_Library (the
  * USB MSC class - usbd_msc_bot.c/usbd_msc_scsi.c) and Middlewares/.../lwIP
  * (httpd.c). Both trees are regenerated by STM32CubeMX and not tracked in
  * git (see .gitignore) - STORAGE_Read_FS()/STORAGE_Write_FS() still return
  * synchronously to the SCSI command handler exactly as before, and hs->buf
  * is read/written only through memcpy(), never handed to DMA or cache ops
  * directly.
  ******************************************************************************
  */
#ifndef MMC_TRANSFER_H
#define MMC_TRANSFER_H

#include "cmsis_os.h"
#ifdef __cplusplus
extern "C" {
#endif

#include "stm32h7xx_hal.h"

/** eMMC logical block size in bytes (matches STORAGE_BLK_SIZ / FatFs sector size). */
#define MMC_TRANSFER_BLOCK_SIZE   512U

typedef struct{
  uint8_t * buf;
  uint32_t size;
  uint32_t addr;
  TaskHandle_t handle;
  uint8_t operation_type;
}FsDataStruct;

enum memory_operation_type{
  MEM_WRITE,
  MEM_READ
};

void MMC_ProcessRequest(FsDataStruct *dataStruct);

/**
  * @brief  Read blk_len blocks starting at blk_addr into buf.
  * @param  buf: destination buffer (any alignment - copied out of the
  *              internal DMA bounce buffer via memcpy(), never DMA'd into
  *              directly).
  * @param  blk_len: number of MMC_TRANSFER_BLOCK_SIZE blocks to read.
  *              Transferred in chunks if larger than the bounce buffer
  *              (MMC_BOUNCE_BLOCKS in mmc_transfer.c).
  * @param  timeout_ms: wall-clock timeout applied to each chunk's transfer.
  * @retval HAL_OK / HAL_ERROR / HAL_TIMEOUT / HAL_BUSY (another transfer
  *         already in flight on hmmc1 - see mmc_transfer.c re-entrancy guard).
  */
HAL_StatusTypeDef MMC_ReadBlocks(uint8_t *buf, uint32_t blk_addr, uint32_t blk_len, uint32_t timeout_ms);

/**
  * @brief  Write blk_len blocks starting at blk_addr from buf.
  * @param  buf: source buffer (any alignment - copied into the internal DMA
  *              bounce buffer via memcpy() before each chunk's transfer).
  * @param  blk_len: number of MMC_TRANSFER_BLOCK_SIZE blocks to write.
  * @param  timeout_ms: wall-clock timeout applied to each chunk's transfer.
  * @retval HAL_OK / HAL_ERROR / HAL_TIMEOUT / HAL_BUSY
  */
HAL_StatusTypeDef MMC_WriteBlocks(const uint8_t *buf, uint32_t blk_addr, uint32_t blk_len, uint32_t timeout_ms);

#ifdef __cplusplus
}
#endif

#endif /* MMC_TRANSFER_H */
