/**
  ******************************************************************************
  * @file    mmc_transfer.h
  * @brief   DMA-backed, cache-safe wrappers around the eMMC block read/write
  *          used by both the USB MSC storage interface (usbd_storage_if.c)
  *          and the FatFs disk driver (user_diskio.c).
  *
  * Why this exists: the blocking HAL_MMC_ReadBlocks()/HAL_MMC_WriteBlocks()
  * on this HAL version do not use DMA/IDMA at all - they poll the SDMMC
  * RX/TX FIFO word-by-word in a CPU loop (see
  * Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mmc.c, "Read block(s) in
  * polling mode"). Called with HAL_MAX_DELAY, that fully occupies the CPU for
  * the whole transfer - and on the USB MSC path it happens synchronously
  * inside OTG_FS_IRQHandler.
  *
  * These wrappers instead kick off HAL_MMC_ReadBlocks_DMA()/WriteBlocks_DMA()
  * (SDMMC IDMA, no CPU involvement in the byte transfer) and wait for
  * completion signalled by HAL_MMC_RxCpltCallback()/TxCpltCallback()/
  * ErrorCallback(), implemented in mmc_transfer.c, which fire from
  * SDMMC1_IRQn (via the existing HAL_MMC_IRQHandler in stm32h7xx_it.c).
  *
  * NOTE for future FreeRTOS integration: MMC_WaitForComplete() in
  * mmc_transfer.c is the single place that busy-waits today. Once FreeRTOS
  * is available, replace its body with osSemaphoreAcquire()/give it from the
  * same HAL_MMC_*CpltCallback - no caller of MMC_ReadBlocks()/MMC_WriteBlocks()
  * needs to change. The USB MSC callers (usbd_storage_if.c) run inside a
  * hardware ISR (OTG_FS_IRQHandler) and must keep using the spin-wait variant
  * - only FatFs-path callers (user_diskio.c), which run in task/thread
  * context, could switch MMC_WaitForComplete() to a real RTOS wait.
  *
  * Deliberately NOT touched: Middlewares/ST/STM32_USB_Device_Library (the
  * USB MSC class - usbd_msc_bot.c/usbd_msc_scsi.c). That tree is
  * regenerated by STM32CubeMX and not tracked in git (see .gitignore), so
  * STORAGE_Read_FS()/STORAGE_Write_FS() still return synchronously to the
  * SCSI command handler exactly as before - only what happens inside them
  * changed.
  ******************************************************************************
  */
#ifndef MMC_TRANSFER_H
#define MMC_TRANSFER_H

#ifdef __cplusplus
extern "C" {
#endif

#include "stm32h7xx_hal.h"

/** eMMC logical block size in bytes (matches STORAGE_BLK_SIZ / FatFs sector size). */
#define MMC_TRANSFER_BLOCK_SIZE   512U

/**
  * @brief  Read blk_len blocks starting at blk_addr into buf via SDMMC IDMA.
  * @param  buf: destination buffer. Invalidated from D-Cache after transfer,
  *              so the CPU sees what the IDMA (bus master) wrote.
  * @param  blk_len: number of MMC_TRANSFER_BLOCK_SIZE blocks to read.
  * @param  timeout_ms: wall-clock timeout for the whole transfer.
  * @retval HAL_OK / HAL_ERROR / HAL_TIMEOUT / HAL_BUSY (another transfer
  *         already in flight on hmmc1 - see mmc_transfer.c re-entrancy guard).
  */
HAL_StatusTypeDef MMC_ReadBlocks(uint8_t *buf, uint32_t blk_addr, uint32_t blk_len, uint32_t timeout_ms);

/**
  * @brief  Write blk_len blocks starting at blk_addr from buf via SDMMC IDMA.
  * @param  buf: source buffer. Cleaned to D-Cache before transfer, so the
  *              IDMA (bus master) reads what the CPU actually wrote.
  * @param  blk_len: number of MMC_TRANSFER_BLOCK_SIZE blocks to write.
  * @param  timeout_ms: wall-clock timeout for the whole transfer.
  * @retval HAL_OK / HAL_ERROR / HAL_TIMEOUT / HAL_BUSY
  */
HAL_StatusTypeDef MMC_WriteBlocks(const uint8_t *buf, uint32_t blk_addr, uint32_t blk_len, uint32_t timeout_ms);

#ifdef __cplusplus
}
#endif

#endif /* MMC_TRANSFER_H */
